//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

using System.Xml.Serialization;

namespace DotNMap {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(IsNullable=false)]
    public partial class nmaprun {
        
        private scaninfo[] scaninfoField;
        
        private verbose verboseField;
        
        private debugging debuggingField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private runstats runstatsField;
        
        private nmaprunScanner scannerField;
        
        private string argsField;
        
        private string startField;
        
        private string startstrField;
        
        private string versionField;
        
        private string profile_nameField;
        
        private string xmloutputversionField;
        
        /// <remarks/>
        [XmlElement("scaninfo")]
        public scaninfo[] scaninfo {
            get {
                return this.scaninfoField;
            }
            set {
                this.scaninfoField = value;
            }
        }
        
        /// <remarks/>
        public verbose verbose {
            get {
                return this.verboseField;
            }
            set {
                this.verboseField = value;
            }
        }
        
        /// <remarks/>
        public debugging debugging {
            get {
                return this.debuggingField;
            }
            set {
                this.debuggingField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("host", typeof(host))]
        [XmlElement("output", typeof(output))]
        [XmlElement("postscript", typeof(postscript))]
        [XmlElement("prescript", typeof(prescript))]
        [XmlElement("target", typeof(target))]
        [XmlElement("taskbegin", typeof(taskbegin))]
        [XmlElement("taskend", typeof(taskend))]
        [XmlElement("taskprogress", typeof(taskprogress))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        public runstats runstats {
            get {
                return this.runstatsField;
            }
            set {
                this.runstatsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public nmaprunScanner scanner {
            get {
                return this.scannerField;
            }
            set {
                this.scannerField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string args {
            get {
                return this.argsField;
            }
            set {
                this.argsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string startstr {
            get {
                return this.startstrField;
            }
            set {
                this.startstrField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string profile_name {
            get {
                return this.profile_nameField;
            }
            set {
                this.profile_nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string xmloutputversion {
            get {
                return this.xmloutputversionField;
            }
            set {
                this.xmloutputversionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class scaninfo {
        
        private scaninfoType typeField;
        
        private string scanflagsField;
        
        private scaninfoProtocol protocolField;
        
        private string numservicesField;
        
        private string servicesField;
        
        /// <remarks/>
        [XmlAttribute()]
        public scaninfoType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string scanflags {
            get {
                return this.scanflagsField;
            }
            set {
                this.scanflagsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public scaninfoProtocol protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string numservices {
            get {
                return this.numservicesField;
            }
            set {
                this.numservicesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum scaninfoType {
        
        /// <remarks/>
        syn,
        
        /// <remarks/>
        ack,
        
        /// <remarks/>
        bounce,
        
        /// <remarks/>
        connect,
        
        /// <remarks/>
        @null,
        
        /// <remarks/>
        xmas,
        
        /// <remarks/>
        window,
        
        /// <remarks/>
        maimon,
        
        /// <remarks/>
        fin,
        
        /// <remarks/>
        udp,
        
        /// <remarks/>
        sctpinit,
        
        /// <remarks/>
        sctpcookieecho,
        
        /// <remarks/>
        ipproto,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum scaninfoProtocol {
        
        /// <remarks/>
        ip,
        
        /// <remarks/>
        tcp,
        
        /// <remarks/>
        udp,
        
        /// <remarks/>
        sctp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class verbose {
        
        private string levelField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class debugging {
        
        private string levelField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class host {
        
        private status statusField;
        
        private address addressField;
        
        //private object[] itemsField;

        private object[] detailsField;
        
        private times timesField;
        
        private string starttimeField;
        
        private string endtimeField;
        
        private string commentField;
        
        /// <remarks/>
        [XmlElement(Order=0)]
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=1)]
        public address address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("address", typeof(address), Order=2)]
        [XmlElement("distance", typeof(distance), Order=2)]
        [XmlElement("hostnames", typeof(hostnames), Order=2)]
        [XmlElement("hostscript", typeof(hostscript), Order=2)]
        [XmlElement("ipidsequence", typeof(ipidsequence), Order=2)]
        [XmlElement("os", typeof(os), Order=2)]
        [XmlElement("ports", typeof(ports), Order=2)]
        [XmlElement("smurf", typeof(smurf), Order=2)]
        [XmlElement("tcpsequence", typeof(tcpsequence), Order=2)]
        [XmlElement("tcptssequence", typeof(tcptssequence), Order=2)]
        [XmlElement("trace", typeof(trace), Order=2)]
        [XmlElement("uptime", typeof(uptime), Order=2)]
        public object[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Order=3)]
        public times times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string starttime {
            get {
                return this.starttimeField;
            }
            set {
                this.starttimeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string endtime {
            get {
                return this.endtimeField;
            }
            set {
                this.endtimeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class status {
        
        private statusState stateField;
        
        private string reasonField;
        
        private string reason_ttlField;
        
        /// <remarks/>
        [XmlAttribute()]
        public statusState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string reason_ttl {
            get {
                return this.reason_ttlField;
            }
            set {
                this.reason_ttlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum statusState {
        
        /// <remarks/>
        up,
        
        /// <remarks/>
        down,
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        skipped,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class address {
        
        private string addrField;
        
        private addressAddrtype addrtypeField;
        
        private string vendorField;
        
        public address() {
            this.addrtypeField = addressAddrtype.ipv4;
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string addr {
            get {
                return this.addrField;
            }
            set {
                this.addrField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(addressAddrtype.ipv4)]
        public addressAddrtype addrtype {
            get {
                return this.addrtypeField;
            }
            set {
                this.addrtypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum addressAddrtype {
        
        /// <remarks/>
        ipv4,
        
        /// <remarks/>
        ipv6,
        
        /// <remarks/>
        mac,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class distance {
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class hostnames {
        
        private hostname[] hostnameField;
        
        /// <remarks/>
        [XmlElement("hostname")]
        public hostname[] hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class hostname {
        
        private string nameField;
        
        private hostnameType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public hostnameType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum hostnameType {
        
        /// <remarks/>
        user,
        
        /// <remarks/>
        PTR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class hostscript {
        
        private script[] scriptField;
        
        /// <remarks/>
        [XmlElement("script")]
        public script[] script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class script {
        
        private string idField;
        
        private string outputField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class ipidsequence {
        
        private string classField;
        
        private string valuesField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class os {
        
        private portused[] portusedField;
        
        private osmatch[] osmatchField;
        
        private osfingerprint[] osfingerprintField;
        
        /// <remarks/>
        [XmlElement("portused")]
        public portused[] portused {
            get {
                return this.portusedField;
            }
            set {
                this.portusedField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("osmatch")]
        public osmatch[] osmatch {
            get {
                return this.osmatchField;
            }
            set {
                this.osmatchField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("osfingerprint")]
        public osfingerprint[] osfingerprint {
            get {
                return this.osfingerprintField;
            }
            set {
                this.osfingerprintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class portused {
        
        private string stateField;
        
        private portusedProto protoField;
        
        private string portidField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public portusedProto proto {
            get {
                return this.protoField;
            }
            set {
                this.protoField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string portid {
            get {
                return this.portidField;
            }
            set {
                this.portidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum portusedProto {
        
        /// <remarks/>
        ip,
        
        /// <remarks/>
        tcp,
        
        /// <remarks/>
        udp,
        
        /// <remarks/>
        sctp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class osmatch {
        
        private osclass[] osclassField;
        
        private string nameField;
        
        private string accuracyField;
        
        private string lineField;
        
        /// <remarks/>
        [XmlElement("osclass")]
        public osclass[] osclass {
            get {
                return this.osclassField;
            }
            set {
                this.osclassField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class osclass {
        
        private string[] cpeField;
        
        private string vendorField;
        
        private string osgenField;
        
        private string typeField;
        
        private string accuracyField;
        
        private string osfamilyField;
        
        /// <remarks/>
        [XmlElement("cpe")]
        public string[] cpe {
            get {
                return this.cpeField;
            }
            set {
                this.cpeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string osgen {
            get {
                return this.osgenField;
            }
            set {
                this.osgenField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string osfamily {
            get {
                return this.osfamilyField;
            }
            set {
                this.osfamilyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class osfingerprint {
        
        private string fingerprintField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string fingerprint {
            get {
                return this.fingerprintField;
            }
            set {
                this.fingerprintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class ports {
        
        private extraports[] extraportsField;
        
        private port[] portField;
        
        /// <remarks/>
        [XmlElement("extraports")]
        public extraports[] extraports {
            get {
                return this.extraportsField;
            }
            set {
                this.extraportsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("port")]
        public port[] port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class extraports {
        
        private extrareasons[] extrareasonsField;
        
        private string stateField;
        
        private string countField;
        
        /// <remarks/>
        [XmlElement("extrareasons")]
        public extrareasons[] extrareasons {
            get {
                return this.extrareasonsField;
            }
            set {
                this.extrareasonsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class extrareasons {
        
        private string reasonField;
        
        private string countField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class port {
        
        private state stateField;
        
        private owner ownerField;
        
        private service serviceField;
        
        private script[] scriptField;
        
        private portProtocol protocolField;
        
        private string portidField;
        
        /// <remarks/>
        public state state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public owner owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public service service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("script")]
        public script[] script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public portProtocol protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string portid {
            get {
                return this.portidField;
            }
            set {
                this.portidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class state {
        
        private string state1Field;
        
        private string reasonField;
        
        private string reason_ttlField;
        
        private string reason_ipField;
        
        /// <remarks/>
        [XmlAttribute("state")]
        public string state1 {
            get {
                return this.state1Field;
            }
            set {
                this.state1Field = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string reason_ttl {
            get {
                return this.reason_ttlField;
            }
            set {
                this.reason_ttlField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string reason_ip {
            get {
                return this.reason_ipField;
            }
            set {
                this.reason_ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class owner {
        
        private string nameField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class service {
        
        private string[] cpeField;
        
        private string nameField;
        
        private serviceConf confField;
        
        private serviceMethod methodField;
        
        private string versionField;
        
        private string productField;
        
        private string extrainfoField;
        
        private serviceTunnel tunnelField;
        
        private bool tunnelFieldSpecified;
        
        private serviceProto protoField;
        
        private bool protoFieldSpecified;
        
        private string rpcnumField;
        
        private string lowverField;
        
        private string highverField;
        
        private string hostnameField;
        
        private string ostypeField;
        
        private string devicetypeField;
        
        private string servicefpField;
        
        /// <remarks/>
        [XmlElement("cpe")]
        public string[] cpe {
            get {
                return this.cpeField;
            }
            set {
                this.cpeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public serviceConf conf {
            get {
                return this.confField;
            }
            set {
                this.confField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public serviceMethod method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string extrainfo {
            get {
                return this.extrainfoField;
            }
            set {
                this.extrainfoField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public serviceTunnel tunnel {
            get {
                return this.tunnelField;
            }
            set {
                this.tunnelField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool tunnelSpecified {
            get {
                return this.tunnelFieldSpecified;
            }
            set {
                this.tunnelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public serviceProto proto {
            get {
                return this.protoField;
            }
            set {
                this.protoField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool protoSpecified {
            get {
                return this.protoFieldSpecified;
            }
            set {
                this.protoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string rpcnum {
            get {
                return this.rpcnumField;
            }
            set {
                this.rpcnumField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string lowver {
            get {
                return this.lowverField;
            }
            set {
                this.lowverField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string highver {
            get {
                return this.highverField;
            }
            set {
                this.highverField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ostype {
            get {
                return this.ostypeField;
            }
            set {
                this.ostypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string devicetype {
            get {
                return this.devicetypeField;
            }
            set {
                this.devicetypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string servicefp {
            get {
                return this.servicefpField;
            }
            set {
                this.servicefpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum serviceConf {
        
        /// <remarks/>
        [XmlEnum("0")]
        Item0,
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
        
        /// <remarks/>
        [XmlEnum("2")]
        Item2,
        
        /// <remarks/>
        [XmlEnum("3")]
        Item3,
        
        /// <remarks/>
        [XmlEnum("4")]
        Item4,
        
        /// <remarks/>
        [XmlEnum("5")]
        Item5,
        
        /// <remarks/>
        [XmlEnum("6")]
        Item6,
        
        /// <remarks/>
        [XmlEnum("7")]
        Item7,
        
        /// <remarks/>
        [XmlEnum("8")]
        Item8,
        
        /// <remarks/>
        [XmlEnum("9")]
        Item9,
        
        /// <remarks/>
        [XmlEnum("10")]
        Item10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum serviceMethod {
        
        /// <remarks/>
        table,
        
        /// <remarks/>
        probed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum serviceTunnel {
        
        /// <remarks/>
        ssl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum serviceProto {
        
        /// <remarks/>
        rpc,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum portProtocol {
        
        /// <remarks/>
        ip,
        
        /// <remarks/>
        tcp,
        
        /// <remarks/>
        udp,
        
        /// <remarks/>
        sctp,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class smurf {
        
        private string responsesField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string responses {
            get {
                return this.responsesField;
            }
            set {
                this.responsesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class tcpsequence {
        
        private string indexField;
        
        private string difficultyField;
        
        private string valuesField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string difficulty {
            get {
                return this.difficultyField;
            }
            set {
                this.difficultyField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class tcptssequence {
        
        private string classField;
        
        private string valuesField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class trace {
        
        private hop[] hopField;
        
        private string protoField;
        
        private string portField;
        
        /// <remarks/>
        [XmlElement("hop")]
        public hop[] hop {
            get {
                return this.hopField;
            }
            set {
                this.hopField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string proto {
            get {
                return this.protoField;
            }
            set {
                this.protoField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class hop {
        
        private string ttlField;
        
        private string rttField;
        
        private string ipaddrField;
        
        private string hostField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string rtt {
            get {
                return this.rttField;
            }
            set {
                this.rttField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string ipaddr {
            get {
                return this.ipaddrField;
            }
            set {
                this.ipaddrField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class uptime {
        
        private string secondsField;
        
        private string lastbootField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string lastboot {
            get {
                return this.lastbootField;
            }
            set {
                this.lastbootField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class times {
        
        private string srttField;
        
        private string rttvarField;
        
        private string toField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string srtt {
            get {
                return this.srttField;
            }
            set {
                this.srttField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string rttvar {
            get {
                return this.rttvarField;
            }
            set {
                this.rttvarField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class output {
        
        private outputType typeField;
        
        private bool typeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public outputType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum outputType {
        
        /// <remarks/>
        interactive,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class postscript {
        
        private script[] scriptField;
        
        /// <remarks/>
        [XmlElement("script")]
        public script[] script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class prescript {
        
        private script[] scriptField;
        
        /// <remarks/>
        [XmlElement("script")]
        public script[] script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class target {
        
        private string specificationField;
        
        private targetStatus statusField;
        
        private bool statusFieldSpecified;
        
        private targetReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [XmlAttribute()]
        public string specification {
            get {
                return this.specificationField;
            }
            set {
                this.specificationField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public targetStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public targetReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum targetStatus {
        
        /// <remarks/>
        skipped,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum targetReason {
        
        /// <remarks/>
        invalid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class taskbegin {
        
        private string taskField;
        
        private string timeField;
        
        private string extrainfoField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string extrainfo {
            get {
                return this.extrainfoField;
            }
            set {
                this.extrainfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class taskend {
        
        private string taskField;
        
        private string timeField;
        
        private string extrainfoField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string extrainfo {
            get {
                return this.extrainfoField;
            }
            set {
                this.extrainfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class taskprogress {
        
        private string taskField;
        
        private string timeField;
        
        private string percentField;
        
        private string remainingField;
        
        private string etcField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string percent {
            get {
                return this.percentField;
            }
            set {
                this.percentField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string remaining {
            get {
                return this.remainingField;
            }
            set {
                this.remainingField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string etc {
            get {
                return this.etcField;
            }
            set {
                this.etcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType( IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        host,
        
        /// <remarks/>
        output,
        
        /// <remarks/>
        postscript,
        
        /// <remarks/>
        prescript,
        
        /// <remarks/>
        target,
        
        /// <remarks/>
        taskbegin,
        
        /// <remarks/>
        taskend,
        
        /// <remarks/>
        taskprogress,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class runstats {
        
        private finished finishedField;
        
        private hosts hostsField;
        
        /// <remarks/>
        public finished finished {
            get {
                return this.finishedField;
            }
            set {
                this.finishedField = value;
            }
        }
        
        /// <remarks/>
        public hosts hosts {
            get {
                return this.hostsField;
            }
            set {
                this.hostsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class finished {
        
        private string timeField;
        
        private string timestrField;
        
        private string elapsedField;
        
        private string summaryField;
        
        private finishedExit exitField;
        
        private bool exitFieldSpecified;
        
        private string errormsgField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string timestr {
            get {
                return this.timestrField;
            }
            set {
                this.timestrField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string elapsed {
            get {
                return this.elapsedField;
            }
            set {
                this.elapsedField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public finishedExit exit {
            get {
                return this.exitField;
            }
            set {
                this.exitField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool exitSpecified {
            get {
                return this.exitFieldSpecified;
            }
            set {
                this.exitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string errormsg {
            get {
                return this.errormsgField;
            }
            set {
                this.errormsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum finishedExit {
        
        /// <remarks/>
        error,
        
        /// <remarks/>
        success,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( IsNullable=false)]
    public partial class hosts {
        
        private string upField;
        
        private string downField;
        
        private string totalField;
        
        public hosts() {
            this.upField = "0";
            this.downField = "0";
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string up {
            get {
                return this.upField;
            }
            set {
                this.upField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string down {
            get {
                return this.downField;
            }
            set {
                this.downField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum nmaprunScanner {
        
        /// <remarks/>
        nmap,
    }
}
